package com.example.shopeee.views

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import androidx.recyclerview.widget.GridLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.shopeee.R
import com.example.shopeee.adapter.RecyclerViewAdapter
import com.example.shopeee.repository.Item
import com.example.shopeee.controllerMVC.AuthController
import com.example.shopeee.databinding.FirstActivityBinding
import io.realm.Realm
import io.realm.mongodb.App

class FirstActivity : AppCompatActivity() {
    private lateinit var newRecyclerView : RecyclerView
    private lateinit var newArrayList : ArrayList<Item>
    lateinit var itemImage : Array<Int>
    lateinit var heading : Array<String>
    lateinit var id : Array<Long>
    lateinit var quantity : Array<Int>

    var firstBinding : FirstActivityBinding? = null
    lateinit var app : App
    private val appId = "shopeee-zuqyq"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        firstBinding = FirstActivityBinding.inflate(layoutInflater)
        setContentView(R.layout.first_activity)

        //Realm
        Realm.init(this)
        app = App(appId)

        val authHandler = AuthController(this, app)

        firstBinding!!.loginRedirectBtn.setOnClickListener{
            authHandler.handleLoginDialog()
        }

        firstBinding!!.signupRedirectBtn.setOnClickListener{
            authHandler.handleSignupDialog()
        }

        /*findViewById<View>(R.id.loginRedirectBtn).setOnClickListener{
            AuthHandler(this, retrofitInterface).handleLoginDialog() }*/


        /*//MVVM get Items repo(temp)
        val repository = ItemsRepository(ItemsApi())

        GlobalScope.launch(Dispatchers.Main){
            val items = repository.getItems()
            Toast.makeText(this@MainActivity, items.toString(), Toast.LENGTH_LONG).show()
        }*/


        //Items list
        //replace with database array
        itemImage = arrayOf()
        heading = arrayOf()

        newRecyclerView = findViewById(R.id.recyclerView)
        val layoutManager = GridLayoutManager(this, 2)
        newRecyclerView.layoutManager = layoutManager
        newRecyclerView.setHasFixedSize(true)

        newArrayList = arrayListOf<Item>()
        getUserData()


    }

    /* Shopee uses a lot of override, @Override or override method type
    Generated by Dagger - CoroutineModule_...DispatcherFactory
    -init Lazy
    -where does the user data go?
    -add secure login
    -Exceptions/error message when server is not available

    Add logout button
    Add SLS login or sth
    Storing user info in Realm and item info in API!
    Put all strings into xml file
    DB structure: userID has an array of items that will be fetched
    threads- whether it will interept main
    mongodb realm- how to secure login

    MongoDB:
    jervis
    qPfg9k1ydEL7VnVt

    Fragments for items (simple)
    Views for login and sign up (complex)
    */

    private fun getUserData() {
        for(i in itemImage.indices) {
            val item = Item(itemImage[i],heading[i],id[i],quantity[i])
            newArrayList.add(item)
        }
        newRecyclerView.adapter = RecyclerViewAdapter(newArrayList)
    }

    //am i gonna do it in a fragment or view?
    //Create bottom bar nav: https://www.youtube.com/watch?v=L_6poZGNXOo
    /*binding.bottomNavigationView.setOnItemSelectedListener { menuItem ->
        when (menuItem.itemId) {
            R.id.tab1 -> replaceFragment(RecyclerViewFragment1())
            R.id.tab2 -> replaceFragment(RecyclerViewFragment2())
            R.id.logout -> logoutUser()
        }
        true
    }

    private fun replaceFragment(fragment: Fragment) {
        supportFragmentManager.beginTransaction()
                .replace(R.id.fragmentContainer, fragment)
                .commit()
    }

    private fun logoutUser() {
        // Implement your logout logic here, such as clearing user session, navigating to login screen, etc.
        // For example:
        startActivity(Intent(this, LoginActivity::class.java))
        finish() // Close the current activity after logging out
    }*/

}